### ISSUE TITLE
Spins endlessly

### ISSUE THREAD

**Issue by bleonard252** [vulrun/File-Explorer#2]
Just popped a fresh installation under a password-protected directory. Why does the loading circle spin endlessly?

**Comment by webcdn** [comment]
@bleonard252 As this project is developed with single-click update feature. And it fetches the latest version from Github repo for any update. So, please check do your hosting/server php function `file_get_contents` works fine for external URL(s). Also, we integrated **php curl** in the next build.

**Comment by bleonard252** [comment]
`file_get_contents` fails on my server for HTTPS requests. cURL works, though, so I'm looking forward to that! 😄

**Comment by webcdn** [comment]
@bleonard252 Recently, we have released the beta version 2.0.0 Here, we have introduced PHP cURL. Hope you will love it.

Thanks
